Adapting iperf3 to get data easily
Cloud-City-RS/OMNTelcoMetrics pull request #20
Opened 2024-11-06 00:45 UTC by RkShaRkz

This PR is the first in line of the few necessary to implement the whole "perform and send user experience data while not moving" feature.

This focuses on making a new Iperf3 monitor which:
- monitors iperf3 results, 
- rechews (reparses) the last successful iperf3 result 
- sends the chewed data back to the listener that told him to start listening
- continues listening until shutdown()

Since it's kinda getting late, the repo with the ringbuffer will land in this or a new PR tomorrow when I wake up.

2024-11-06 00:45 UTC, RkShaRkz commented
@coderabbitai review

2024-11-06 00:52 UTC, RkShaRkz reviewed
LGTM actually, but do address these comments.

2024-11-06 00:52 UTC, RkShaRkz commented on app/src/main/java/cloudcity/CloudCityUtil.java
> +
none of this seems necessary. remove

2024-11-06 00:52 UTC, RkShaRkz commented on app/src/main/java/cloudcity/dataholders/MetricsPOJO.java
> +//                '}';
can get rid. can leave it in. no need to leave it in tho.

delete this garbage.

2024-11-06 00:52 UTC, RkShaRkz commented on app/src/main/java/de/fraunhofer/fokus/OpenMobileNetworkToolkit/Iperf3/Iperf3Fragment.java
> +            iperf3BiDir.setChecked(true);
some holder for this data would have been better but it does the trick for now. leave it like this.

2024-11-06 00:52 UTC, RkShaRkz commented on app/src/main/java/cloudcity/Iperf3Monitor.java
> +//                        throw new RuntimeException(e);
eh. remove.

2024-11-06 00:52 UTC, RkShaRkz commented on app/src/main/java/cloudcity/Iperf3Monitor.java
> +                                    double ULlast = getLast(defaultThroughput.getMeanList()) / 1e+6;
consider extracting all this dividing into a 
```
public double normalize(double value) {
    return value / 1e+6;
}
```
method... dunno why I didn't want to do it immediatelly, but i remember not wanting to do it for some reason. can't remember which, so I was wrong.

2024-11-06 00:52 UTC, RkShaRkz commented on app/src/main/java/cloudcity/Iperf3Monitor.java
> +                            double ULmean = defaultThroughput.calcMean() / 1e+6;
DRY violation right there :D

2024-11-06 00:52 UTC, RkShaRkz commented on app/src/main/java/cloudcity/Iperf3Monitor.java
> +                    Log.wtf(TAG, "Starting parsing...");
eh...

2024-11-06 00:52 UTC, RkShaRkz commented on app/src/main/java/cloudcity/Iperf3Monitor.java
> +                Log.d(TAG, "startParsingThread()::parsingCycle!\tshouldStop: " + shouldStop.get());
verbose. Log.v

2024-11-06 06:32 UTC, slavkof requested changes
Ima materijala da se dotera

2024-11-06 12:39 UTC, RkShaRkz reviewed
LGTM, but take another peek after commiting the CR commit since I was addressing them as I was going through this.

2024-11-06 12:39 UTC, RkShaRkz commented on app/src/main/java/cloudcity/Iperf3Monitor.java
> +    }
fair point, done. also, should be synchronized. resolving.

2024-11-06 12:39 UTC, RkShaRkz commented on app/src/main/java/cloudcity/Iperf3Monitor.java
> +//                        throw new RuntimeException(e);
done. resolving.

2024-11-06 12:39 UTC, RkShaRkz commented on app/src/main/java/cloudcity/Iperf3Monitor.java
> +//                        throw new RuntimeException(e);
actually, will still throw if it happens.

2024-11-06 12:39 UTC, RkShaRkz commented on app/src/main/java/cloudcity/Iperf3Monitor.java
> +
throwing RuntimeException above will do that, resolving.

2024-11-06 12:39 UTC, RkShaRkz commented on app/src/main/java/cloudcity/Iperf3Monitor.java
> +                                    double ULlast = getLast(defaultThroughput.getMeanList()) / 1e+6;
done, resolving.

2024-11-06 12:39 UTC, RkShaRkz commented on app/src/main/java/cloudcity/Iperf3Monitor.java
> +                            double ULmean = defaultThroughput.calcMean() / 1e+6;
done, normalized. resolving.

2024-11-06 12:39 UTC, RkShaRkz commented on app/src/main/java/cloudcity/Iperf3Monitor.java
> +                    Log.wtf(TAG, "Starting parsing...");
done. resolving.

2024-11-06 12:39 UTC, RkShaRkz commented on app/src/main/java/cloudcity/Iperf3Monitor.java
> +                Log.d(TAG, "startParsingThread()::parsingCycle!\tshouldStop: " + shouldStop.get());
done. resolving.

2024-11-06 12:39 UTC, RkShaRkz commented on app/src/main/java/cloudcity/dataholders/MetricsPOJO.java
> +    private final double ULlast;
nope, but will add class-level javadoc. resolving.

2024-11-06 12:39 UTC, RkShaRkz commented on app/src/main/java/cloudcity/dataholders/MetricsPOJO.java
> +    }
nope, but will do something else. resolving.

2024-11-06 12:39 UTC, RkShaRkz commented on app/src/main/java/cloudcity/dataholders/MetricsPOJO.java
> +//                '}';
deleted. resolving.

2024-11-06 12:39 UTC, RkShaRkz commented on app/src/main/java/de/fraunhofer/fokus/OpenMobileNetworkToolkit/Iperf3/Iperf3Fragment.java
> +        });
done. but not in this file. and no try/catch either. resolving.

2024-11-06 12:39 UTC, RkShaRkz commented on app/src/main/java/de/fraunhofer/fokus/OpenMobileNetworkToolkit/Iperf3/Iperf3Parser.java
> +    public static final Object END_MARKER = new Object();
get rid of this.

2024-11-06 12:39 UTC, RkShaRkz commented on app/src/main/java/de/fraunhofer/fokus/OpenMobileNetworkToolkit/Iperf3/Iperf3Parser.java
> +    public static final Object END_MARKER = new Object();
or you know what, just let it sit for a while, and when it causes conflicts then delete it. it's just used as a marker value to fire the "end" property change so we see when the parsing is over.

2024-11-06 12:39 UTC, RkShaRkz commented on app/src/main/java/de/fraunhofer/fokus/OpenMobileNetworkToolkit/Iperf3/Iperf3Parser.java
> +            Log.e(TAG, "File not found!!! Path to file: "+pathToFile);
not necessary, we don't want to change their original code too much. lets see if it's an issue first.

wont change, resolving.

2024-11-06 12:39 UTC, RkShaRkz commented on app/src/main/java/de/fraunhofer/fokus/OpenMobileNetworkToolkit/Iperf3/Iperf3Parser.java
> +                        Log.v(TAG, "Encountered START");
nope, but instead od silently swallowing, we'll also log it as an error.

resolving.

2024-11-06 12:39 UTC, RkShaRkz commented on app/src/main/java/de/fraunhofer/fokus/OpenMobileNetworkToolkit/Iperf3/Iperf3ResultsDataBase.java
> +    public static Iperf3ResultsDataBase getDatabase(final Context context) {
nope, won't do any of this. this file was changed only so we can instantiate it from outside of the package.
resolving.

2024-11-07 06:50 UTC, slavkof approved these changes

2024-11-08 11:35 UTC, merged